name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install x11 dev libs
      run: sudo apt-get update && sudo apt-get install -y libx11-dev libxrandr-dev libxinerama-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
