name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cmake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "3.25.1"
    - name: install x11 dev libs
      run: sudo apt-get update && sudo apt install libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: cmake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "3.25.1"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
